#!/bin/bash

set -euo pipefail

usage() {
    echo "session USERNAME PASSWORD"
    exit 1
}

[[ "$#" -lt 2 ]] && usage

declare -r USERNAME="$1" && shift
declare -r PASSWORD="$1"

pushd $(mktemp -d) > /dev/null

curl -siL -XPOST \
  http://pac.fil.cool/uglix/bin/login/stp \
  -H 'Content-Type: application/json' \
  -d "{
	\"username\": \"$USERNAME\"
}" > "uname.log"

declare -r COOKIE=$(grep -Fi "Set-Cookie" uname.log | cut -d: -f2- | cut -d\  -f2- | rev | cut -c2- | rev)
declare -r UNAME=$(cat uname.log | tail -n1)

declare -r KEY="$PASSWORD-$UNAME"
echo "$KEY"

echo '{
    "method": "GET",
    "url": "/bin/login/stp/handshake"
}' > "request.json"

openssl enc -aes-128-cbc -md sha256 -pass pass:"$KEY" -in "request.json" -out "request.json.bin"

curl -siL -XPOST \
  http://pac.fil.cool/uglix/bin/gateway \
  -H 'Content-Type: application/octet-stream' \
  -H "Cookie: $COOKIE" \
  --data-binary @request.json.bin > "handshake.log"

grep -Fi "Set-Cookie" "handshake.log" | cut -d: -f2- | cut -d\  -f2- | rev | cut -c2- | rev

popd > /dev/null
