#!/bin/bash

set -euo pipefail

usage() {
    echo "session KEY SESSION_COOKIE [REQUEST_FILE...]"
    exit 1
}

[ "$#" -lt 2 ] && usage

declare -r KEY="$1" && shift
declare -r COOKIE="$1" && shift

send_request() {
    set -euo pipefail

    local FILE

    if [[ "$1" = "-" ]]; then
        FILE=$(mktemp)
        cat > "$FILE"
    else
        if [[ -f "$1" && -r "$1" ]]; then
            FILE="$1"
        else
            echo "Cannot upload '$1'. Skipping."
            return
        fi
    fi

    local CRYPTED=$(mktemp)
    openssl enc -aes-128-cbc -md sha256 -pass pass:"$KEY" -in "$FILE" -out "$CRYPTED"

    local RESPONSE=$(mktemp)

    curl -sL -XPOST \
        http://pac.fil.cool/uglix/bin/uVM/7900fc2a/gateway \
        -H 'Content-Type: application/octet-stream' \
        -H "Cookie: $COOKIE" \
        --data-binary "@$CRYPTED" \
        -o "$RESPONSE"

    # cat $RESPONSE

    if [[ -s "$RESPONSE" ]]; then
        openssl enc -d -aes-128-cbc -md sha256 -pass pass:"$KEY" -in "$RESPONSE"
    else
        echo "OK"
    fi
}

main() {
    set -euo pipefail

    if [[ $# -eq 0 ]]; then
        send_request "-"
    else
        while [[ $# -ne 0 ]]
        do
            send_request "$1"
            shift
        done
    fi
}

main "$@"
