CC=gcc
CFLAGS=-Wall

state-iv: state-iv.o

state-iv2: state-iv2.o

state-iv-64: state-iv-64.o

seed: seed.o drand48.o

key-iv: key-iv.o drand48.o

clean:
	rm *.o seed state-iv state-iv2 state-iv-64 key-iv
